import {
  faArrowRight,
  faArrowTrendUp,
  faAward,
  faBarsProgress,
  faBookOpen,
  faBullseye,
  faChartColumn,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleQuestion,
  faClock,
  faCog,
  faLayerGroup,
  faLock,
  faFloppyDisk,
  faPen,
  faShieldHalved,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserGroup,
  faUserSlash,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { faCircle } from '@fortawesome/free-regular-svg-icons';

/**
 * FontAwesome icons
 */

export const iconLibrary = {
  progressBarsIcon: faBarsProgress,
  userIcon: faUser,
  userGroupIcon: faUserGroup,
  openBookIcon: faBookOpen,
  groupLayerIcon: faLayerGroup,
  chartColumnIcon: faChartColumn,
  cogIcon: faCog,
  lockIcon: faLock,
  targetIcon: faBullseye,
  awardIcon: faAward,
  trendUpIcon: faArrowTrendUp,
  arrowRightIcon: faArrowRight,
  clockIcon: faClock,
  penIcon: faPen,
  trashIcon: faTrash,
  saveIcon: faFloppyDisk,
  keyIcon: faLock,
  userSlashIcon: faUserSlash,
  exchangeIcon: faArrowRight,
  checkCircleIcon: faCircleCheck,
  circleRegularIcon: faCircle,
  closeIcon: faXmark,
  chevronLeftIcon: faChevronLeft,
  chevronRightIcon: faChevronRight,
  warningIcon: faTriangleExclamation,
  questionCircleIcon: faCircleQuestion,
  shieldIcon: faShieldHalved,
};
